### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by NaughtyChas** [NaughtyChas/ThePuzzleGame#1]
This issue is a development roadmap. Key points of development will be listed:

- [x] Confirm what kind of game we're going to develop
- [x] Draft a outline and structure about the program
- [x] Code factoring
- [x] Alpha stage
- [x] Beta stage

**Comment by NaughtyChas** [comment]
We've decided the gametype. See our Notion workspace for more info.

**Comment by NaughtyChas** [comment]
> * [x]  Draft a outline and structure about the program

ofc now we have to:

- [x] **Creates the main game menu**: allows the player to select the game mode and difficulty.
- [x] **Initialize the game grid**: set the grid size and trap density according to the selected difficulty.
- [x] **Implementing the cell reveal function**: click on a cell to reveal its contents.
- [x] **Implement letter and trap logic**: defines the behavior of letters and traps and their effects.
- [x] **Implementation of the hint system**: display the number of letters contained in the surrounding cells.
- [x] **Implementation of the word formation and scoring system**: allows the player to select letters to form words and calculate the score.
- [x] **Implementation of a game over condition**: defines the conditions for the end of the game.
- [x] **Implementation of a statistics system**: record and display player statistics.
- ~~**Implementation of an Achievement and Badge System**: reward players for their achievements. (TBD)~~  (*Closed as Not planned*)

**Comment by NaughtyChas** [comment]
Project finished, congrats!

As for the coding submission part, you can simply choose to download source code as a zip file from the master branch. You can find this at the green `<> code` button on top right.

All objectives has been completed based on the requirement of group project criteria, from now on all opening issues are being targeted as "Future Interest", if I would like to step back and do something fun.
